contrast: 100
backlight_power: 55
init_line_1: "init line 1"
init_line_2: "init line 2"
init_line_3: "init line 3"
init_line_4: "init line 4"
red_led_1: 0.0
green_led_1: 0.0
red_led_2: 0.0
green_led_2: 0.0
red_led_3: 0.0
green_led_3: 0.0
red_led_4: 0.0
green_led_4: 0.0
